# Generated by Django 3.1.2 on 2020-10-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turno', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('docCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientes')),
                ('idTurno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.turnos')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Angendas',
            },
        ),
    ]
