# Generated by Django 3.1.2 on 2020-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('docCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('primerApellido', models.CharField(max_length=70)),
                ('segundoApellido', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=150)),
                ('celular', models.CharField(max_length=12)),
                ('fechaNacimiento', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
