# Generated by Django 3.1.2 on 2020-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=12, verbose_name='Celular '),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='docCliente',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=150, verbose_name=' Correo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombres',
            field=models.CharField(max_length=70, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='primerApellido',
            field=models.CharField(max_length=70, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='segundoApellido',
            field=models.CharField(max_length=70, verbose_name='Segundo Apellido'),
        ),
    ]
