# Generated by Django 3.1.2 on 2020-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='./static/image')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
