# Generated by Django 3.1.2 on 2020-10-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('idTurno', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('seleccionado', models.IntegerField(verbose_name=0)),
                ('docEmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleados')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
