# Generated by Django 3.1.2 on 2020-10-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('docmp', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('primerApellido', models.CharField(max_length=70)),
                ('segundoApellido', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('celular', models.CharField(max_length=70)),
                ('fechaNacimiento', models.DateField(auto_now=True)),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicios')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
            },
        ),
    ]
